name: Build Server exe
on: [push]

env:
  BUILD_TYPE: Release
  
jobs:
  build:
    name: Build Server exe
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      uses: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload GitHub Actions artifact of vcpkg build
      uses: actions/upload-artifact@v3.1.2
      with:
        name: soggy-win
        path: ${{ github.workspace }}/build/
