name: Build Server exe

on:
  push:
    branches: [ "mistress" ]
  pull_request:
    branches: [ "mistress" ]

jobs:
  build:
    name: "Build Server exe"
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2

    - shell: msys2 {0}
      name: Configure CMake
      run: |
       pacman -S ${MINGW_PACKAGE_PREFIX}-{cmake,protobuf,lua}
       cmake -B build -G "Unix Makefiles"
      
    - shell: msys2 {0}
      name: Build
      run: cmake --build build -j8

    - name: Upload soggy latest artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: soggy-windows
        path: ./build/soggy.exe
